apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-tycx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-tycx
    app.kubernetes.io/part-of: integ-app-gydh
  name: devfile-sample-python-basic-tycx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-tycx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-tycx
    spec:
      containers:
      - image: quay.io/bootstrap/integration-e2e-tenant/integ-app-gydh/devfile-sample-python-basic-tycx@sha256:d88d38aa82e0fc32246ce48a159a39746a8cd8b810137f636d25e37b390604b3
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
